(setq ring-bell-function 'ignore)
(setq custom-file "~/.emacs.d/custom.el")
(scroll-bar-mode -1)
(load-theme 'modus-operandi t)

(require 'package)
(package-initialize)
(unless (package-installed-p 'setup)
  (package-install 'setup))

(setup (:package which-key)
  (which-key-mode 1))
(setup (:package vertico)
  (:package marginalia)
  (vertico-mode 1)
  (marginalia-mode 1)
  (define-key vertico-map (kbd "TAB") #'minibuffer-complete))
(setup (:package corfu)
  (:option corfu-auto t)
  (:option global-corfu-mode t))
(setup (:package eglot))
(setup LaTeX
  (:package auctex)
  (:option TeX-save-query nil))
(setup text-mode
  (:hook flyspell-mode auto-fill-mode))
(setup (:package rust-mode))
(setup (:package sly)
  (:option inferior-lisp-program "clisp"))
(electric-pair-mode t)
